kpTAD<-function(kp,hicPobj){
  chr=seqlevels(hicPobj$cMap[1])
  kpSegments(kp,chr=chr,x0=start(hicPobj$cMap),x1=hicPobj$cMap$edge,
             y0=0,y1=hicPobj$cMap$Ys,r0=at$r0,
             r1=at$r1,col=hicPobj$cMap$colors,lwd=hicPobj$param$lwdP,lty=hicPobj$param$ltyP)
  kpSegments(kp,chr=chr,x0=hicPobj$cMap$edge,x1=end(hicPobj$cMap),
             y0=hicPobj$cMap$Ys,y1=0,r0=at$r0,
             r1=at$r1,col=hicPobj$cMap$colors,lwd=hicPobj$param$lwdP,lty=hicPobj$param$ltyP)
  }
